# Allowed date format: Month D, YYYY
# Example valid: November 1, 2025
# Invalid examples: November 01, 2025  or Nov 1, 2025
allowed_months:
  - January
  - February
  - March
  - April
  - May
  - June
  - July
  - August
  - September
  - October
  - November
  - December

# Regex for allowed date token in the file. Must match the entire date token.
# Explanation: full month name, a space, day without leading zero (1-31), comma, space, 4-digit year
allowed_date_regex: "^(January|February|March|April|May|June|July|August|September|October|November|December) (?:[1-9]|[12][0-9]|3[01]), \\d{4}$"
